### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by tomasbargut** [Pra3t0r5/giftedRecruits#1]
Ayuda!

I have this projects as a core dependency. 
I need to know if is this still maintained. Please give me some answers
I'm in panic!

Thanks

**Comment by Pra3t0r5** [comment]
You should panic and freak out, a lot. This is not mantained since Q2 2018.

**Comment by Pra3t0r5** [comment]
Oh god, just noticed where you implemented this, we are all going to die! Revert, quickly!
